SELECT TOP (10) [OrderId]
      ,[CustomerId]
      ,[EmployeeId]
      ,[OrderDate]
      ,[RequiredDate]
      ,[ShippedDate]
      ,[ShipVia]
      ,[Freight]
      ,[ShipName]
      ,[ShipAddress]
      ,[ShipCity]
      ,[ShipRegion]
      ,[ShipPostalCode]
      ,[ShipCountry]
  FROM [Northwind24_93_HVR].[dbo].[Orders]
  ORDER BY OrderId DESC